name: build + tests

on:
  pull_request:
  push:
    paths-ignore:
      - ".github/workflows/format.yml"
      - "**/docs/**"
      - "**/README.md"
      - "**/CHANGELOG.md"
      - "**/LICENSE"
      - "**/.gitignore"
      - "**/.clang-format"

jobs:
  pre-job:
    runs-on: ubuntu-latest
    outputs:
      should_skip: ${{ steps.skip_check.outputs.should_skip }}
    steps:
      - id: skip_check
        uses: fkirc/skip-duplicate-actions@v3.4.0
        with:
          cancel_others: true

  build-ubuntu:
    needs: pre-job
    if: ${{ needs.pre-job.outputs.should_skip != 'true' }}
    runs-on: ubuntu-latest

    env:
      CC: gcc-10
      CXX: g++-10

    strategy:
      matrix:
        arch: [x64]
        mode: [debug, release]

    steps:
      - uses: actions/checkout@v2

      # Install xmake
      - name: Setup xmake
        uses: xmake-io/github-action-setup-xmake@v1

      # Configure
      - name: Configure
        run: xmake f -a ${{ matrix.arch }} -m ${{ matrix.mode }} -yv

      # Build
      - name: Build
        run: xmake

      # Run tests
      - name: Test
        run: xmake test

  build-epitest:
    needs: pre-job
    if: ${{ needs.pre-job.outputs.should_skip != 'true' }}
    runs-on: ubuntu-latest
    container: epitechcontent/epitest-docker

    strategy:
      matrix:
        arch: [x64]
        mode: [debug, release]

    steps:
      - uses: actions/checkout@v2

      # Install xmake
      - name: Setup xmake
        uses: xmake-io/github-action-setup-xmake@v1

      # Configure
      - name: Configure
        run: xmake f -a ${{ matrix.arch }} -m ${{ matrix.mode }} -yv

      # Build
      - name: Build
        run: xmake

      # Run tests
      - name: Test
        run: xmake test

  build-windows:
    needs: pre-job
    if: ${{ needs.pre-job.outputs.should_skip != 'true' }}
    runs-on: windows-latest

    strategy:
      matrix:
        arch: [x64]
        mode: [debug, release]

    steps:
      - uses: actions/checkout@v2

      # Install xmake
      - name: Setup xmake
        uses: xmake-io/github-action-setup-xmake@v1

      # Configure
      - name: Configure
        run: xmake f -a ${{ matrix.arch }} -m ${{ matrix.mode }} -yv

      # Build
      - name: Build
        run: xmake

      # Run tests
      - name: Test
        run: xmake test
