name: Build and run tests

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Configure
        run: cmake -DCMAKE_BUILD_TYPE=Release -B build
      - name: Build
        run: cmake --build build
      - name: Test
        working-directory: build
        run: ctest

  build-epitest:
    needs: [build]
    runs-on: ubuntu-latest
    if: ${{ github.ref == 'refs/heads/master' }}
    container: epitechcontent/epitest-docker
    steps:
      - uses: actions/checkout@v2
      - name: Configure
        run: cmake -DCMAKE_BUILD_TYPE=Release -B build
      - name: Build
        run: cmake --build build
      - name: Test
        working-directory: build
        run: ctest

  build-windows:
    needs: [build]
    runs-on: windows-latest
    if: ${{ github.ref == 'refs/heads/master' }}
    steps:
      - uses: actions/checkout@v2
      - name: Configure
        run: cmake -DCMAKE_BUILD_TYPE=Release -B build
      - name: Build
        run: cmake --build build
      - name: Test
        working-directory: build
        run: ctest
