name: build + tests

on:
  push:
  pull_request:

jobs:
  pre-job:
    runs-on: ubuntu-latest
    outputs:
      should_skip: ${{ steps.skip_check.outputs.should_skip }}
    steps:
      - id: skip_check
        uses: fkirc/skip-duplicate-actions@v3.4.0
        with:
          cancel_others: true
          paths_ignore: >
            [
              "**/docs/**",
              "**/README.md",
              "**/CHANGELOG.md",
              "**/LICENSE",
              "**/.gitignore",
              "**/.clang-format"
            ]

  build-ubuntu:
    needs: pre-job
    if: ${{ needs.pre-job.outputs.should_skip != 'true' }}
    runs-on: ubuntu-latest
    env:
      CC: gcc-10
      CXX: g++-10
      LIBNYQUIST_ASOUND: 1
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: sudo apt install xorg-dev
      - name: Configure
        run: cmake -DCMAKE_BUILD_TYPE=Release -B build
      - name: Build
        run: cmake --build build -j 2
      - name: Test
        working-directory: build
        run: ctest

  build-epitest:
    needs: pre-job
    if: ${{ needs.pre-job.outputs.should_skip != 'true' }}
    runs-on: ubuntu-latest
    env:
      LIBNYQUIST_ASOUND: 1
    container: epitechcontent/epitest-docker
    steps:
      - uses: actions/checkout@v2
      - name: Configure
        run: cmake -DCMAKE_BUILD_TYPE=Release -B build
      - name: Build
        run: cmake --build build -j 2
      - name: Test
        working-directory: build
        run: ctest

  build-windows:
    needs: pre-job
    if: ${{ needs.pre-job.outputs.should_skip != 'true' }}
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - name: Configure
        run: cmake -DCMAKE_BUILD_TYPE=Release -B build
      - name: Build
        run: cmake --build build -j 2
      - name: Test
        working-directory: build
        run: ctest
