name: build + tests

on:
  push:
  pull_request:

jobs:
  build-ubuntu:
    runs-on: ubuntu-latest
    env:
      CC: gcc-10
      CXX: g++-10
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: sudo apt install xorg-dev
      - name: Configure
        run: cmake -DCMAKE_BUILD_TYPE=Release -B build
      - name: Build
        run: cmake --build build
      - name: Test
        working-directory: build
        run: ctest

  build-epitest:
    runs-on: ubuntu-latest
    if: ${{ github.ref == 'refs/heads/master' }}
    container: epitechcontent/epitest-docker
    steps:
      - uses: actions/checkout@v2
      - name: Configure
        run: cmake -DCMAKE_BUILD_TYPE=Release -B build
      - name: Build
        run: cmake --build build
      - name: Test
        working-directory: build
        run: ctest

  build-windows:
    runs-on: windows-latest
    needs: [build-epitest]
    if: ${{ github.ref == 'refs/heads/master' }}
    steps:
      - uses: actions/checkout@v2
      - name: Configure
        run: cmake -DCMAKE_BUILD_TYPE=Release -B build
      - name: Build
        run: cmake --build build
      - name: Test
        working-directory: build
        run: ctest
