name: Check coding style with clang-format

on:
  push:
  pull_request:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install clang-format
        run: |
          sudo apt-get install clang-format
          clang-format --version
      - name: Check for clang-format errors
        run: >
          find -type f \( -iname "*.cpp" -o -iname "*.hpp" \)
          -exec clang-format --Werror --style=file --dry-run {} +
